import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import { PrimeReactProvider } from 'primereact/api';
import 'primereact/resources/themes/lara-light-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import ClientProvider from '@/services/config/ClientProvider';
import Provider from '@/redux/provider';
import { PrimeReactI18nProvider } from '@/services/config/i18n';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const value = {
    locale: 'pt-BR',
  };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider>
          <Provider>
            <PrimeReactI18nProvider>
              <PrimeReactProvider value={value}>{children}</PrimeReactProvider>
            </PrimeReactI18nProvider>
          </Provider>
        </ClientProvider>
      </body>
    </html>
  );
}
